"""initial schema

Revision ID: 06f2887fb63b
Revises: 
Create Date: 2026-09-01 20:56:06.453886
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '06f2887fb63b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=150), nullable=True),
    sa.Column('business_unit', sa.String(length=150), nullable=True),
    sa.Column('primary_url', sa.String(length=500), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('data_sensitivity', sa.String(length=20), nullable=False),
    sa.Column('exposure', sa.String(length=30), nullable=False),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_reference'), 'assets', ['reference'], unique=True)
    op.create_table('enrichment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('cache_key', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrichment_cache'))
    )
    op.create_index(op.f('ix_enrichment_cache_expires_at'), 'enrichment_cache', ['expires_at'], unique=False)
    op.create_index('ix_enrichment_source_key', 'enrichment_cache', ['source', 'cache_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=180), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engagement_type', sa.String(length=60), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_assessments_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    op.create_index(op.f('ix_assessments_client_name'), 'assessments', ['client_name'], unique=False)
    op.create_index(op.f('ix_assessments_created_at'), 'assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessments_created_by_id'), 'assessments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_assessments_is_demo'), 'assessments', ['is_demo'], unique=False)
    op.create_index(op.f('ix_assessments_name'), 'assessments', ['name'], unique=False)
    op.create_index(op.f('ix_assessments_reference'), 'assessments', ['reference'], unique=True)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=60), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_assessment_id'), 'audit_logs', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_created_at'), 'system_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('assessment_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_assessment', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_members_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_members')),
    sa.UniqueConstraint('assessment_id', 'user_id', name='assessment_user')
    )
    op.create_index(op.f('ix_assessment_members_assessment_id'), 'assessment_members', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_members_user_id'), 'assessment_members', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('storage_backend', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=40), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_reports_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_assessment_id'), 'reports', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_format'), 'reports', ['format'], unique=False)
    op.create_index(op.f('ix_reports_reference'), 'reports', ['reference'], unique=True)
    op.create_table('scope_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_scope_rules_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scope_rules_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_rules'))
    )
    op.create_index(op.f('ix_scope_rules_assessment_id'), 'scope_rules', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_scope_rules_created_at'), 'scope_rules', ['created_at'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('base_path', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('authorization_confirmed', sa.Boolean(), nullable=False),
    sa.Column('authorization_statement', sa.Text(), nullable=True),
    sa.Column('authorized_by_id', sa.Integer(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_targets_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_targets_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], name=op.f('fk_targets_authorized_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targets'))
    )
    op.create_index(op.f('ix_targets_assessment_id'), 'targets', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_targets_asset_id'), 'targets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_targets_created_at'), 'targets', ['created_at'], unique=False)
    op.create_index(op.f('ix_targets_hostname'), 'targets', ['hostname'], unique=False)
    op.create_index(op.f('ix_targets_reference'), 'targets', ['reference'], unique=True)
    op.create_index(op.f('ix_targets_status'), 'targets', ['status'], unique=False)
    op.create_index(op.f('ix_targets_value'), 'targets', ['value'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('endpoint', sa.String(length=600), nullable=True),
    sa.Column('parameter', sa.String(length=200), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('request_snippet', sa.Text(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('remediation_recommendation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('primary_source', sa.String(length=40), nullable=False),
    sa.Column('data_origin', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('correlation_key', sa.String(length=128), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_hits', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=140), nullable=True),
    sa.Column('cvss_version', sa.String(length=10), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('cwe_name', sa.String(length=240), nullable=True),
    sa.Column('cve_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cve_details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('likelihood', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_findings_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_findings_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_findings_target_id_targets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_findings_verified_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_assessment_id'), 'findings', ['assessment_id'], unique=False)
    op.create_index('ix_findings_assessment_severity', 'findings', ['assessment_id', 'severity'], unique=False)
    op.create_index('ix_findings_assessment_status', 'findings', ['assessment_id', 'status'], unique=False)
    op.create_index(op.f('ix_findings_assigned_to_id'), 'findings', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index('ix_findings_correlation', 'findings', ['assessment_id', 'correlation_key'], unique=False)
    op.create_index(op.f('ix_findings_correlation_key'), 'findings', ['correlation_key'], unique=False)
    op.create_index(op.f('ix_findings_created_at'), 'findings', ['created_at'], unique=False)
    op.create_index(op.f('ix_findings_cvss_score'), 'findings', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_findings_cwe_id'), 'findings', ['cwe_id'], unique=False)
    op.create_index(op.f('ix_findings_data_origin'), 'findings', ['data_origin'], unique=False)
    op.create_index(op.f('ix_findings_is_demo'), 'findings', ['is_demo'], unique=False)
    op.create_index(op.f('ix_findings_primary_source'), 'findings', ['primary_source'], unique=False)
    op.create_index(op.f('ix_findings_priority'), 'findings', ['priority'], unique=False)
    op.create_index(op.f('ix_findings_reference'), 'findings', ['reference'], unique=True)
    op.create_index(op.f('ix_findings_risk_level'), 'findings', ['risk_level'], unique=False)
    op.create_index(op.f('ix_findings_risk_score'), 'findings', ['risk_score'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_sla_due_at'), 'findings', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_target_id'), 'findings', ['target_id'], unique=False)
    op.create_index(op.f('ix_findings_verification_status'), 'findings', ['verification_status'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_operation', sa.String(length=240), nullable=True),
    sa.Column('requested_scanners', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('raw_findings_count', sa.Integer(), nullable=False),
    sa.Column('duplicates_merged', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_runner', sa.String(length=20), nullable=True),
    sa.Column('task_id', sa.String(length=80), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_scan_jobs_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scan_jobs_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_scan_jobs_target_id_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    op.create_index(op.f('ix_scan_jobs_assessment_id'), 'scan_jobs', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_created_at'), 'scan_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_jobs_created_by_id'), 'scan_jobs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_reference'), 'scan_jobs', ['reference'], unique=True)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_target_id'), 'scan_jobs', ['target_id'], unique=False)
    op.create_table('target_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], name=op.f('fk_target_endpoints_target_id_targets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_endpoints'))
    )
    op.create_index(op.f('ix_target_endpoints_created_at'), 'target_endpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_target_endpoints_target_id'), 'target_endpoints', ['target_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('annotations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence.id'], name=op.f('fk_evidence_supersedes_id_evidence'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_evidence_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_evidence_storage_key'))
    )
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_file_hash'), 'evidence', ['file_hash'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('finding_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_comments_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finding_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_comments'))
    )
    op.create_index(op.f('ix_finding_comments_created_at'), 'finding_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_finding_comments_finding_id'), 'finding_comments', ['finding_id'], unique=False)
    op.create_table('finding_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_history_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_finding_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_history'))
    )
    op.create_index(op.f('ix_finding_history_created_at'), 'finding_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_finding_history_event_type'), 'finding_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_finding_history_finding_id'), 'finding_history', ['finding_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('developer_notes', sa.Text(), nullable=True),
    sa.Column('fix_summary', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_for_retest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_remediations_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_remediations_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediations_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediations'))
    )
    op.create_index(op.f('ix_remediations_assigned_to_id'), 'remediations', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_remediations_created_at'), 'remediations', ['created_at'], unique=False)
    op.create_index(op.f('ix_remediations_finding_id'), 'remediations', ['finding_id'], unique=True)
    op.create_index(op.f('ix_remediations_priority'), 'remediations', ['priority'], unique=False)
    op.create_index(op.f('ix_remediations_sla_due_at'), 'remediations', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_remediations_status'), 'remediations', ['status'], unique=False)
    op.create_table('scanner_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('command_summary', sa.Text(), nullable=True),
    sa.Column('raw_findings_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tool_version', sa.String(length=80), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_scanner_runs_scan_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scanner_runs'))
    )
    op.create_index(op.f('ix_scanner_runs_created_at'), 'scanner_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scanner_runs_scan_job_id'), 'scanner_runs', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_scanner_runs_scanner'), 'scanner_runs', ['scanner'], unique=False)
    op.create_table('finding_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('scanner', sa.String(length=40), nullable=False),
    sa.Column('scanner_run_id', sa.Integer(), nullable=True),
    sa.Column('scan_job_id', sa.Integer(), nullable=True),
    sa.Column('raw_title', sa.String(length=300), nullable=True),
    sa.Column('raw_severity', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_sources_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_finding_sources_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanner_run_id'], ['scanner_runs.id'], name=op.f('fk_finding_sources_scanner_run_id_scanner_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_sources'))
    )
    op.create_index(op.f('ix_finding_sources_created_at'), 'finding_sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_finding_sources_finding_id'), 'finding_sources', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_sources_scanner'), 'finding_sources', ['scanner'], unique=False)
    op.create_index(op.f('ix_finding_sources_scanner_run_id'), 'finding_sources', ['scanner_run_id'], unique=False)
    op.create_table('retests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_retests_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_retests_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], name=op.f('fk_retests_performed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], name=op.f('fk_retests_remediation_id_remediations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retests'))
    )
    op.create_index(op.f('ix_retests_created_at'), 'retests', ['created_at'], unique=False)
    op.create_index(op.f('ix_retests_finding_id'), 'retests', ['finding_id'], unique=False)
    op.create_index(op.f('ix_retests_result'), 'retests', ['result'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retests_result'), table_name='retests')
    op.drop_index(op.f('ix_retests_finding_id'), table_name='retests')
    op.drop_index(op.f('ix_retests_created_at'), table_name='retests')
    op.drop_table('retests')
    op.drop_index(op.f('ix_finding_sources_scanner_run_id'), table_name='finding_sources')
    op.drop_index(op.f('ix_finding_sources_scanner'), table_name='finding_sources')
    op.drop_index(op.f('ix_finding_sources_finding_id'), table_name='finding_sources')
    op.drop_index(op.f('ix_finding_sources_created_at'), table_name='finding_sources')
    op.drop_table('finding_sources')
    op.drop_index(op.f('ix_scanner_runs_scanner'), table_name='scanner_runs')
    op.drop_index(op.f('ix_scanner_runs_scan_job_id'), table_name='scanner_runs')
    op.drop_index(op.f('ix_scanner_runs_created_at'), table_name='scanner_runs')
    op.drop_table('scanner_runs')
    op.drop_index(op.f('ix_remediations_status'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_sla_due_at'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_priority'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_finding_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_created_at'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_assigned_to_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_finding_history_finding_id'), table_name='finding_history')
    op.drop_index(op.f('ix_finding_history_event_type'), table_name='finding_history')
    op.drop_index(op.f('ix_finding_history_created_at'), table_name='finding_history')
    op.drop_table('finding_history')
    op.drop_index(op.f('ix_finding_comments_finding_id'), table_name='finding_comments')
    op.drop_index(op.f('ix_finding_comments_created_at'), table_name='finding_comments')
    op.drop_table('finding_comments')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_file_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_target_endpoints_target_id'), table_name='target_endpoints')
    op.drop_index(op.f('ix_target_endpoints_created_at'), table_name='target_endpoints')
    op.drop_table('target_endpoints')
    op.drop_index(op.f('ix_scan_jobs_target_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_reference'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_created_by_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_created_at'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_assessment_id'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_findings_verification_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_target_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_sla_due_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_risk_score'), table_name='findings')
    op.drop_index(op.f('ix_findings_risk_level'), table_name='findings')
    op.drop_index(op.f('ix_findings_reference'), table_name='findings')
    op.drop_index(op.f('ix_findings_priority'), table_name='findings')
    op.drop_index(op.f('ix_findings_primary_source'), table_name='findings')
    op.drop_index(op.f('ix_findings_is_demo'), table_name='findings')
    op.drop_index(op.f('ix_findings_data_origin'), table_name='findings')
    op.drop_index(op.f('ix_findings_cwe_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cvss_score'), table_name='findings')
    op.drop_index(op.f('ix_findings_created_at'), table_name='findings')
    op.drop_index(op.f('ix_findings_correlation_key'), table_name='findings')
    op.drop_index('ix_findings_correlation', table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_assigned_to_id'), table_name='findings')
    op.drop_index('ix_findings_assessment_status', table_name='findings')
    op.drop_index('ix_findings_assessment_severity', table_name='findings')
    op.drop_index(op.f('ix_findings_assessment_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_targets_value'), table_name='targets')
    op.drop_index(op.f('ix_targets_status'), table_name='targets')
    op.drop_index(op.f('ix_targets_reference'), table_name='targets')
    op.drop_index(op.f('ix_targets_hostname'), table_name='targets')
    op.drop_index(op.f('ix_targets_created_at'), table_name='targets')
    op.drop_index(op.f('ix_targets_asset_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_assessment_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_scope_rules_created_at'), table_name='scope_rules')
    op.drop_index(op.f('ix_scope_rules_assessment_id'), table_name='scope_rules')
    op.drop_table('scope_rules')
    op.drop_index(op.f('ix_reports_reference'), table_name='reports')
    op.drop_index(op.f('ix_reports_format'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_assessment_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_assessment_members_user_id'), table_name='assessment_members')
    op.drop_index(op.f('ix_assessment_members_assessment_id'), table_name='assessment_members')
    op.drop_table('assessment_members')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_created_at'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_audit_user_time', table_name='audit_logs')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_assessment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_reference'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_name'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_is_demo'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_by_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_client_name'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_enrichment_source_key', table_name='enrichment_cache')
    op.drop_index(op.f('ix_enrichment_cache_expires_at'), table_name='enrichment_cache')
    op.drop_table('enrichment_cache')
    op.drop_index(op.f('ix_assets_reference'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
