"""add ai triage cache to findings

Revision ID: c65a5f51070a
Revises: 06f2887fb63b
Create Date: 2026-09-02 12:36:59.887980
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c65a5f51070a'
down_revision = '06f2887fb63b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('ai_triage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('findings', sa.Column('ai_triage_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'ai_triage_at')
    op.drop_column('findings', 'ai_triage')
    # ### end Alembic commands ###
